version: "3.7"

services:
  account:
    build:
      context: .
      dockerfile: 
    depends_on:
      - 
    environment:
      DATABASE_URL:
      SERVICE_PORT:
    restart: 

  catalog:
    build:
      context: 
      dockerfile: 
    depends_on:
    - 
    environment:
      DATABASE_URL: 
      SERVICE_PORT: 
    restart: 

  order:
    build:
      context: .
      dockerfile: 
    depends_on:
      - 
    environment:
      DATABASE_URL: 
      ACCOUNT_SERVICE_URL: 
      CATALOG_SERVICE_URL: 
      SERVICE_PORT: 
    restart : 

  graphql:
    build:
      context: .
      dockerfile: 
    ports:
      - 8000:8000
    depends_on:
      - account
      - catalog
      - order
    environment:
      ACCOUNT_SERVICE_URL: "http://account:8000"
      CATALOG_SERVICE_URL: "http://catalog:8000"
      ORDER_SERVICE_URL: "http://order:8000"
    restart: on-failure

  account_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: <DB_NAME>
      POSTGRES_USER: <USERNAME>
      POSTGRES_PASSWORD: <PASSWORD>
    ports:
      - "5432:5432"
    restart: unless-stopped

  catalog_db:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      discovery.type: single-node

  order_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: <DB_NAME>
      POSTGRES_USER: <USERNAME>
      POSTGRES_PASSWORD: <PASSWORD>
    ports:
      - "5433:5432"
    restart: unless-stopped
